services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: jobtracker
      POSTGRES_PASSWORD: jobtracker
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
