"""add confirmed field to jobs

Revision ID: a2be7c376c05
Revises: 1d946b206ace
Create Date: 2026-06-02 15:23:48.744305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2be7c376c05'
down_revision: Union[str, Sequence[str], None] = '1d946b206ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('confirmed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'confirmed')
    # ### end Alembic commands ###
